# Site settings
baseurl = "www.veganitee.com/"
languageCode = "en-us"
title = "Hugrid - Grid Theme For Hugo"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "VeganiTee - Vegan merch for all!"
    subtitle = "Vegan family of seven. We try to live authentically and be kind to others, which includes animals. We make t-shirts to spread the #vegan love. ❤ ️🌱 #GoVegan"
    author = "VeganiTee"
    description = "Vegan family of seven. We try to live authentically and be kind to others, which includes animals. We make t-shirts to spread the #vegan love. ❤ ️🌱 #GoVegan"
    keywords = "Hugo, Hugo theme, grid theme, portfolio, bookmarks, collection, contacts"

    # Body background color
    bodybgcolor = "#0006c00"

    # Preview container button text
    buttontext = "Shop it!"

    # Footer text
    footertext = "Made by [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/), [Hugo](http://gohugo.io) and [me](https://github.com/aerohub)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
